--- #YAML:1.0
name:                Tree-DAG_Node-XPath
version:             0.10
abstract:            Add XPath support to Tree::DAG_Node
license:             perl
author:              
    - Michel Rodriguez <mirod@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Tree::DAG_Node:                1.04
    Tree::XPathEngine:             0.05
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
